kind: Deployment
apiVersion: apps/v1
metadata:
  name: test2-app
  labels:
    app: app1
spec:
  replicas: 4
  selector:
    matchLabels:
      app: app1
  template:
    metadata:
      labels:
        app: app1
    spec:
      containers:
      - image: nginx
        name: cont1
        ports:
        - name: http
          containerPort: 80
